### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by demiurg** [vincentsarago/color-operations#4]
Thank you for the effort with this package, and rio-tiler. I was trying to use micromamba on arm64, and I think I'm stuck not being able to conda install rio-tiler from conda-forge, because there is no arm64 version of this color-operations package.

I know this is a niche usecase, but I thought I should at least mention this. I also can see this package is cython, and builds for osx, which I assume might include arm support. So, maybe it's not a lot of effort to add arm64 as build target.

I'm not sure how to do this, but let me know if you have any interest in adding arm64 support.

**Comment by vincentsarago** [comment]
I though we were creating the wheels for arm64 https://github.com/vincentsarago/color-operations/blob/main/.github/workflows/ci.yml#L80 🤔 

https://files.pythonhosted.org/packages/33/f1/f5309fbedb59a1d3dc4be419b5daf8316a219d0fb64dc12158994bf33269/color_operations-0.1.1-cp311-cp311-macosx_11_0_arm64.whl

**Comment by vincentsarago** [comment]
oh you mean non MacOS arm64 🤦

**Comment by demiurg** [comment]
yes :) AWS Graviton, specifically. In dockerfile that looks like linux/amd64/v8 or `--platform linux/arm64`

**Comment by vincentsarago** [comment]
I'm not an expert in how we create wheels but everything is done using https://cibuildwheel.readthedocs.io/en/stable/ if you want to have a look

**Comment by demiurg** [comment]
Thanks, I'll take a look!

**Comment by vincentsarago** [comment]
@demiurg did you look more into this? 🙏

**Comment by demiurg** [comment]
My bad, thanks for reminder. I forgot about this. But, having looked at the cibuildwheel, it appears that the lines in these examples can be added?
```
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x
```
from https://github.com/pypa/cibuildwheel/blob/main/examples/github-with-qemu.yml#L27
